FROM debian:bookworm-slim

ARG TARGETARCH

RUN apt-get update && apt-get install -y --no-install-recommends ca-certificates && \
    rm -rf /var/lib/apt/lists/*

COPY bin/${TARGETARCH}/oxi-dns /usr/local/bin/oxi-dns
COPY config.toml /etc/oxi-dns/config.toml

RUN chmod 755 /usr/local/bin/oxi-dns

EXPOSE 53/udp 53/tcp 853/tcp 853/udp 443/tcp 9853/tcp 9854/tcp

ENTRYPOINT ["oxi-dns", "/etc/oxi-dns/config.toml"]
